name: SFMM
author: Idra
description: Custom machines for MetaMechanists

main: org.metamechanists.SFMM
website: www.metamechanists.org
version: 0.7
api-version: 1.19

depend:
  - Slimefun
  - Networks
  - InfinityExpansion
  - ExoticGarden
  - FoxyMachines
  - Galactifun
  - ExtraTools